-- Roles and permissions (framework/backend/api/base/permissions.ts), matching
-- the tables TBWC got in its own migration 039 so both apps share one shape.
--
-- Replaces two things: the users.role string, which requirePermission special-
-- cased ('admin' bypassed every check), and the per-user users.permissions
-- jsonb, which had to be regenerated per user whenever a role's meaning changed.
-- Roles now hold grants as rows, so adding one is an INSERT and a few ticked
-- boxes in Settings > Roles.
--
-- tenant_id is the isolation boundary: NULL = a system role every tenant sees,
-- set = private to that tenant. The seeded roles below are all system roles;
-- tenant-created ones carry their tenant's id. The framework's lookup admits
-- only system-or-own-tenant and fails closed on a mismatch.
--
-- Nothing may branch on role.code — roles are user-creatable, so any such check
-- would silently exclude every role made later.

CREATE TABLE IF NOT EXISTS public.role (
  role_id    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id  integer REFERENCES public.tenant(tenant_id) ON DELETE CASCADE,
  code       text NOT NULL,
  name       text NOT NULL,
  is_system  boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Two partial indexes: a plain UNIQUE (tenant_id, code) would never catch two
-- system roles sharing a code, since NULL doesn't collide with itself.
CREATE UNIQUE INDEX IF NOT EXISTS role_code_system_uniq
  ON public.role (code) WHERE tenant_id IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS role_code_tenant_uniq
  ON public.role (tenant_id, code) WHERE tenant_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.role_permission (
  role_permission_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_id            integer NOT NULL REFERENCES public.role(role_id) ON DELETE CASCADE,
  permission         text NOT NULL,
  scope              text NOT NULL DEFAULT 'all' CHECK (scope IN ('all', 'own')),
  hidden_fields      text[] NOT NULL DEFAULT '{}',
  UNIQUE (role_id, permission)
);

CREATE INDEX IF NOT EXISTS role_permission_role_idx ON public.role_permission (role_id);

-- No ON DELETE action: a role still assigned to someone can't be deleted, so
-- deleting one forces reassigning its users rather than stranding them with no
-- permissions at all.
ALTER TABLE public.users
  ADD COLUMN IF NOT EXISTS role_id integer REFERENCES public.role(role_id),
  ADD COLUMN IF NOT EXISTS permission_overrides jsonb;

COMMENT ON COLUMN public.users.permission_overrides IS
  'Per-user adjustments over the role: {"meter:update": "own"} narrows or grants, {"meter:update": false} revokes. Meant to stay rare.';

-- Same blanket-RLS-no-policies stance as 038-enable-rls-all-tables.sql: the
-- Worker connects at service level and bypasses RLS, nothing else gets in.
ALTER TABLE public.role            ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.role_permission ENABLE ROW LEVEL SECURITY;

-- --- seed -------------------------------------------------------------------
--
-- Codes match the values users.role actually stores (the users_role_check
-- constraint from migration 040), which is the whole point of this seed: the
-- old in-code map was keyed 'Manager'/'Technician'/'Viewer' while the column
-- and the UI use lowercase, so getPermissionsByRole() missed on every non-admin
-- role and silently returned Viewer's permissions. Managers and technicians
-- have been running with viewer access.

INSERT INTO public.role (code, name, is_system) VALUES
  ('admin',        'Administrator', true),
  ('manager',      'Manager',       true),
  ('technician',   'Technician',    true),
  ('viewer',       'Viewer',        true),
  ('user',         'User',          true),
  ('superadmin',   'Super Admin',   true),
  ('supersupport', 'Super Support', true)
ON CONFLICT DO NOTHING;

-- admin + superadmin + supersupport: the whole catalog. The platform flags
-- (is_super_admin/is_support_admin) still bypass separately for cross-tenant
-- work; this is what they get as ordinary tenant users.
INSERT INTO public.role_permission (role_id, permission, scope)
SELECT r.role_id, p.permission, 'all'
  FROM public.role r
 CROSS JOIN (VALUES
    ('dashboard:admin'), ('dashboard:create'), ('dashboard:delete'), ('dashboard:read'), ('dashboard:update'),
    ('contact:create'), ('contact:delete'), ('contact:read'), ('contact:update'),
    ('device:read'),
    ('email:read'), ('email:send'),
    ('location:create'), ('location:delete'), ('location:read'), ('location:update'),
    ('meter:create'), ('meter:delete'), ('meter:read'), ('meter:update'),
    ('notification:read'), ('notification:send'),
    ('settings:read'), ('settings:update'),
    ('template:create'), ('template:delete'), ('template:read'), ('template:update'),
    ('user:create'), ('user:delete'), ('user:read'), ('user:update'),
    ('role:read'), ('role:write')
  ) AS p(permission)
 WHERE r.tenant_id IS NULL AND r.code IN ('admin', 'superadmin', 'supersupport')
ON CONFLICT (role_id, permission) DO NOTHING;

-- manager: full CRUD on the operational modules, read-only settings, no role
-- management, and the dashboard/email/notification access the old map forgot.
INSERT INTO public.role_permission (role_id, permission, scope)
SELECT r.role_id, p.permission, 'all'
  FROM public.role r
 CROSS JOIN (VALUES
    ('dashboard:create'), ('dashboard:delete'), ('dashboard:read'), ('dashboard:update'),
    ('contact:create'), ('contact:delete'), ('contact:read'), ('contact:update'),
    ('device:read'),
    ('email:read'), ('email:send'),
    ('location:create'), ('location:delete'), ('location:read'), ('location:update'),
    ('meter:create'), ('meter:delete'), ('meter:read'), ('meter:update'),
    ('notification:read'), ('notification:send'),
    ('settings:read'),
    ('template:create'), ('template:read'), ('template:update'),
    ('user:read'), ('user:update')
  ) AS p(permission)
 WHERE r.tenant_id IS NULL AND r.code = 'manager'
ON CONFLICT (role_id, permission) DO NOTHING;

-- technician: works the equipment, doesn't administer it.
INSERT INTO public.role_permission (role_id, permission, scope)
SELECT r.role_id, p.permission, 'all'
  FROM public.role r
 CROSS JOIN (VALUES
    ('dashboard:read'),
    ('contact:read'),
    ('device:read'),
    ('location:read'),
    ('meter:read'), ('meter:update'),
    ('notification:read'),
    ('template:read')
  ) AS p(permission)
 WHERE r.tenant_id IS NULL AND r.code = 'technician'
ON CONFLICT (role_id, permission) DO NOTHING;

-- viewer + user: read-only. 'user' had no entry in the old map at all and fell
-- through to Viewer, so seeding them alike preserves what it resolved to.
INSERT INTO public.role_permission (role_id, permission, scope)
SELECT r.role_id, p.permission, 'all'
  FROM public.role r
 CROSS JOIN (VALUES
    ('dashboard:read'),
    ('contact:read'),
    ('device:read'),
    ('location:read'),
    ('meter:read'),
    ('notification:read'),
    ('settings:read'),
    ('template:read')
  ) AS p(permission)
 WHERE r.tenant_id IS NULL AND r.code IN ('viewer', 'user')
ON CONFLICT (role_id, permission) DO NOTHING;

-- Backfill: point every user at the system role matching the string they
-- already carry. Anything unrecognised lands on viewer, which is what
-- getPermissionsByRole()'s fallback did.
UPDATE public.users u
   SET role_id = r.role_id
  FROM public.role r
 WHERE r.tenant_id IS NULL
   AND r.code = CASE
         WHEN u.role IN ('admin', 'manager', 'technician', 'viewer', 'user',
                         'superadmin', 'supersupport') THEN u.role
         ELSE 'viewer'
       END
   AND u.role_id IS NULL;
