-- ===== Canonical `ai_memory` table (framework-owned) =====
-- Backs the AI chat's persistent memory: framework/backend/api/base/aiMemory.ts
-- maps Anthropic's client-side memory tool (memory_20250818) onto this table.
-- Claude sees a virtual /memories directory; each row is one "file" keyed by
-- its full path (e.g. /memories/schema.md). Directories are implicit from
-- path prefixes, there are no directory rows.
--
-- tenant_id scopes the store: multi-tenant apps (MeterItPro) FK it to
-- `tenant` and pass the caller's tenant; single-tenant apps (TBWC) leave it
-- NULL, giving one shared store for the whole portal. NULLS NOT DISTINCT
-- (Postgres 15+) keeps path unique within the NULL-tenant store too, which
-- the ON CONFLICT upsert in aiMemory.ts relies on.

CREATE TABLE IF NOT EXISTS public.ai_memory (
    ai_memory_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id integer,
    path varchar(500) NOT NULL,
    content text NOT NULL DEFAULT '',
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ai_memory_tenant_path_key UNIQUE NULLS NOT DISTINCT (tenant_id, path),
    CONSTRAINT ai_memory_path_check CHECK (path LIKE '/memories/%')
);

-- Worker connects as the service role and bypasses RLS; anon/authenticated
-- via PostgREST get nothing.
ALTER TABLE public.ai_memory ENABLE ROW LEVEL SECURITY;
