-- ===== Canonical `role` / `role_permission` tables (framework-owned) =====
-- Backs Settings > Roles: framework/backend/api/base/roles.ts (route logic),
-- framework/backend/api/base/permissions.ts (runtime enforcement),
-- framework/frontend/components/settings/RolesForm.tsx (UI).
--
-- A role holds `module:action` grants as rows, each with a scope (all = every
-- row, own = only the caller's) and fields to strip from responses — so "reps
-- see their own orders without the money columns" is data, not code. Roles
-- are creatable at runtime: adding one is an INSERT plus grant rows, no
-- deploy. That only holds as long as no app code branches on role.code or an
-- is_admin-style boolean — checks go against permissions, never a role's
-- name, or every role created after the check would be silently excluded.
--
-- tenant_id is the isolation boundary for a multi-tenant app: NULL = a system
-- role every tenant sees and (per framework/backend/api/base/roles.ts's
-- ownership rule) only a superadmin-style flow ever edits; set = private to
-- that tenant. A single-tenant app has no `tenant` table to reference — drop
-- the REFERENCES clause below and every role that app creates simply lands
-- with tenant_id NULL, which roles.ts treats as "no tenant concept, every
-- role is mutable" (see that file's header comment). TBWC is the
-- single-tenant case; MeterItPro is the multi-tenant one.
--
-- Consuming apps copy this file into their own migrations dir (TBWC:
-- migrations/039-roles-and-permissions.sql, MeterItPro:
-- migrations/053-roles-and-permissions.sql — both already applied; this file
-- is the shared source of truth going forward, edit here first).
-- Naming convention: {tablename}_id primary key.

CREATE TABLE IF NOT EXISTS public.role (
  role_id    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- Multi-tenant apps: `tenant_id integer REFERENCES public.tenant(tenant_id) ON DELETE CASCADE`.
  -- Single-tenant apps: plain `tenant_id integer` (always NULL).
  tenant_id  integer,
  code       text NOT NULL,
  name       text NOT NULL,
  -- Seeded roles the app assumes exist: blocked from deletion/rename in the UI.
  is_system  boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Two partial indexes: a plain UNIQUE (tenant_id, code) would never catch two
-- system roles (or, single-tenant, any two roles) sharing a code, since NULL
-- doesn't collide with itself.
CREATE UNIQUE INDEX IF NOT EXISTS role_code_system_uniq
  ON public.role (code) WHERE tenant_id IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS role_code_tenant_uniq
  ON public.role (tenant_id, code) WHERE tenant_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.role_permission (
  role_permission_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_id            integer NOT NULL REFERENCES public.role(role_id) ON DELETE CASCADE,
  -- A 'module:action' string from the app's own catalog. Not constrained
  -- here: the catalog lives in app code, and resolvePermissions() ignores any
  -- grant outside it, so a stale row can never widen access past what routes
  -- enforce.
  permission         text NOT NULL,
  scope              text NOT NULL DEFAULT 'all' CHECK (scope IN ('all', 'own')),
  -- Response fields this role may not see for that module. Legacy — prefer
  -- field_access below for new grants (same effect via view:false, plus
  -- edit, which this never had); kept so existing grants and routes that
  -- read it directly keep working unchanged.
  hidden_fields      text[] NOT NULL DEFAULT '{}',
  -- Per-field view/edit: {"sold_for": {"view": false}, "lines[].rate": {"edit": false}}.
  -- Omitted field = full access. See permissions.ts's hiddenFields()/readOnlyFields().
  field_access       jsonb NOT NULL DEFAULT '{}'::jsonb,
  UNIQUE (role_id, permission)
);

-- Existing installs (this table predates field_access): add the column
-- without touching any row. TBWC: migrations/064-field-access.sql.
-- MeterItPro: migrations/055-field-access.sql.
ALTER TABLE public.role_permission
  ADD COLUMN IF NOT EXISTS field_access jsonb NOT NULL DEFAULT '{}'::jsonb;

CREATE INDEX IF NOT EXISTS role_permission_role_idx ON public.role_permission (role_id);

-- No ON DELETE action: a role still assigned to someone can't be deleted, so
-- deleting one forces reassigning its users first rather than silently
-- stranding them with no permissions at all.
ALTER TABLE public.users
  ADD COLUMN IF NOT EXISTS role_id integer REFERENCES public.role(role_id),
  ADD COLUMN IF NOT EXISTS permission_overrides jsonb;

COMMENT ON COLUMN public.users.permission_overrides IS
  'Per-user adjustments over the role: {"order:write": "own"} narrows or grants, {"order:write": false} revokes. Meant to stay rare.';

-- Same blanket-RLS-no-policies stance as every other framework-owned table:
-- the Worker connects as superuser/service role and bypasses RLS, while
-- anon/authenticated via PostgREST get nothing.
ALTER TABLE public.role            ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.role_permission ENABLE ROW LEVEL SECURITY;

-- Seed data (system roles + their grants + backfilling users.role_id from
-- whatever the app used before) is app-specific and stays in each app's own
-- migration — TBWC/api/migrations/039-roles-and-permissions.sql and
-- MeterItPro/api/migrations/053-roles-and-permissions.sql, not here.
