-- ===== Canonical `support_ticket` table (framework-owned) =====
-- Backs the Support module: framework/backend/api/base/supportTicketSchema.ts
-- (form schema) and framework/frontend/support/* (ticket list + detail UI).
-- Each app's own worker/routes/support*.ts wraps the shared
-- framework/backend/api/base/crud.ts findAll/findById/create/update against
-- this table — there is no framework-owned route module, since CRUD + a
-- visibility filter is all a ticket needs and crud.ts already covers both.
--
-- tenant_id / client_tenant_id follow the same split as
-- framework/backend/db/role.sql: tenant_id is the *support-providing* org
-- (fixed; who the ticket is filed TO) and client_tenant_id is who filed it.
-- Multi-tenant apps (MeterItPro) FK both to `tenant` and scope a non-admin
-- caller's ticket list by `client_tenant_id = caller.tenant_id` (everyone at
-- that client org sees the org's tickets). Single-tenant apps (TBWC) have no
-- `tenant` table — both columns stay plain integers, always NULL, and
-- non-admin visibility instead scopes by `users_id = caller.id` (the ticket's
-- own creator), since there is no second org to partition by. An app-level
-- "support admin" caller (MeterItPro: users.is_support_admin;
-- TBWC: support:write permission) always sees every ticket regardless.
--
-- users_id / assigned_to_users_id reference each app's own users PK — an
-- integer users_id (MeterItPro) or a uuid id (TBWC, Supabase Auth). Copy this
-- file into your migrations dir and adjust that FK's column/type accordingly.
-- Naming convention: {tablename}_id primary key.

CREATE TABLE IF NOT EXISTS public.support_ticket (
    support_ticket_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id integer,
    client_tenant_id integer,
    -- Multi-tenant: `users_id integer REFERENCES public.users(users_id)`,
    -- `assigned_to_users_id integer REFERENCES public.users(users_id)`.
    -- Single-tenant / Supabase Auth: `users_id uuid REFERENCES public.users(id)`,
    -- `assigned_to_users_id uuid REFERENCES public.users(id)`.
    users_id integer,
    assigned_to_users_id integer,
    title  varchar(200),
    description text,
    type  varchar(30) NOT NULL DEFAULT 'general',
    status  varchar(20) NOT NULL DEFAULT 'open',
    priority  varchar(20) NOT NULL DEFAULT 'medium',
    resolved_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT support_ticket_type_check CHECK (type::text = ANY (ARRAY['bug'::text, 'feature_request'::text, 'billing'::text, 'account'::text, 'technical'::text, 'general'::text])),
    CONSTRAINT support_ticket_status_check CHECK (status::text = ANY (ARRAY['open'::text, 'in_progress'::text, 'resolved'::text, 'closed'::text])),
    CONSTRAINT support_ticket_priority_check CHECK (priority::text = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'urgent'::text]))
);

CREATE INDEX IF NOT EXISTS idx_support_ticket_tenant_id ON public.support_ticket USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_support_ticket_client_tenant_id ON public.support_ticket USING btree (client_tenant_id);
CREATE INDEX IF NOT EXISTS idx_support_ticket_users_id ON public.support_ticket USING btree (users_id);
CREATE INDEX IF NOT EXISTS idx_support_ticket_status ON public.support_ticket USING btree (status);
CREATE INDEX IF NOT EXISTS idx_support_ticket_created_at ON public.support_ticket USING btree (created_at);

-- Same blanket-RLS-no-policies stance as every other framework-owned table:
-- the Worker connects as superuser/service role and bypasses RLS, while
-- anon/authenticated via PostgREST get nothing.
ALTER TABLE public.support_ticket ENABLE ROW LEVEL SECURITY;

-- First installed in MeterItPro as migrations/041 (table), 049 (RLS enable,
-- added after 038's blanket enable had already run and missed this table
-- since it didn't exist yet) — see those files for the original multi-tenant
-- FK shape. TBWC: migrations/067-support-ticket.sql (single-tenant shape).
