-- Roles and permissions (framework/backend/api/base/permissions.ts).
--
-- Replaces the single users.is_admin boolean, which could only ever express two
-- kinds of person and had to be hand-checked in every route. A role holds
-- `module:action` grants as rows, each with a scope (all = every row, own = only
-- the caller's) and fields to strip from responses — so "reps see their own
-- orders without the money columns" becomes data instead of code.
--
-- Roles are creatable at runtime: adding one is an INSERT plus grant rows, no
-- deploy. That only holds as long as no code branches on role.code — checks go
-- against permissions, never against a role's name, or every role created after
-- the check would be silently excluded from it.
--
-- tenant_id is always NULL here (TBWC is single-tenant). The column exists so
-- both apps share one table shape and the framework's tenant-guarded lookup runs
-- unmodified; in MeterItPro a non-NULL tenant_id makes a role private to that
-- tenant.
--
-- This migration deliberately preserves today's access exactly: admin keeps
-- everything, and the three non-admin roles are seeded identically to what a
-- non-admin can do right now. Differentiating employee from rep is a decision to
-- make in the admin UI afterwards, not a behaviour change smuggled into a
-- migration.

CREATE TABLE IF NOT EXISTS public.role (
  role_id    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id  integer,
  code       text NOT NULL,
  name       text NOT NULL,
  -- Seeded roles the app assumes exist: blocked from deletion/rename in the UI.
  is_system  boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Codes are unique per owner; two partial indexes because NULL tenant_id would
-- otherwise never collide with itself in a plain UNIQUE (tenant_id, code).
CREATE UNIQUE INDEX IF NOT EXISTS role_code_system_uniq
  ON public.role (code) WHERE tenant_id IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS role_code_tenant_uniq
  ON public.role (tenant_id, code) WHERE tenant_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.role_permission (
  role_permission_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_id            integer NOT NULL REFERENCES public.role(role_id) ON DELETE CASCADE,
  -- A 'module:action' string from the app's catalog. Not constrained here: the
  -- catalog lives in code, and resolvePermissions() ignores any grant outside
  -- it, so a stale row can never widen access past what routes enforce.
  permission         text NOT NULL,
  scope              text NOT NULL DEFAULT 'all' CHECK (scope IN ('all', 'own')),
  -- Response fields this role may not see for that module.
  hidden_fields      text[] NOT NULL DEFAULT '{}',
  UNIQUE (role_id, permission)
);

CREATE INDEX IF NOT EXISTS role_permission_role_idx ON public.role_permission (role_id);

-- No ON DELETE action: a role still assigned to someone cannot be deleted, so
-- deleting one forces reassigning its users first rather than silently
-- stranding them with no permissions at all.
ALTER TABLE public.users
  ADD COLUMN IF NOT EXISTS role_id integer REFERENCES public.role(role_id),
  ADD COLUMN IF NOT EXISTS permission_overrides jsonb;

COMMENT ON COLUMN public.users.permission_overrides IS
  'Per-user adjustments over the role: {"order:write": "own"} narrows or grants, {"order:write": false} revokes. Meant to stay rare.';

-- Same blanket-RLS-no-policies stance as every other table here: the Worker
-- connects as superuser and bypasses RLS, while anon/authenticated via PostgREST
-- get nothing. Enabled in the creating migration on purpose — 001-005 not doing
-- so is exactly how thirteen tables ended up publicly readable (see 007).
ALTER TABLE public.role            ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.role_permission ENABLE ROW LEVEL SECURITY;

-- --- seed -------------------------------------------------------------------

INSERT INTO public.role (code, name, is_system) VALUES
  ('admin',    'Administrator', true),
  ('employee', 'Employee',      true),
  ('rep',      'Sales Rep',     true),
  ('customer', 'Customer',      true)
ON CONFLICT DO NOTHING;

-- Admin: the whole catalog, unscoped. Matches is_admin today.
INSERT INTO public.role_permission (role_id, permission, scope)
SELECT r.role_id, p.permission, 'all'
  FROM public.role r
 CROSS JOIN (VALUES
    ('order:read'), ('order:write'), ('order:delete'),
    ('quote:read'), ('quote:write'), ('quote:delete'),
    ('invoice:read'),
    ('customer:read'),
    ('inventory:read'), ('inventory:write'),
    ('user:read'), ('user:write'),
    ('setting:read'), ('setting:write'),
    ('document:read'), ('document:write'),
    ('qbsync:read'), ('qbsync:run'),
    ('aichat:use'),
    ('dashboard:read')
  ) AS p(permission)
 WHERE r.code = 'admin' AND r.tenant_id IS NULL
ON CONFLICT (role_id, permission) DO NOTHING;

-- Non-admins, seeded to exactly what they can reach today: their own orders and
-- invoices read-only, their own quotes, the catalog and documents read-only.
--
-- One deliberate tightening: the order money columns are listed as hidden here
-- because they are NOT actually hidden today. The rep order form drops them via
-- the schema's visibleFor: ['admin'], but that is presentation only — GET
-- /api/orders selects qb_sales_order.*, so every rep response already carries
-- sold_for, commission and the rest in its JSON. hidden_fields makes the server
-- enforce what the form was only pretending to.
INSERT INTO public.role_permission (role_id, permission, scope, hidden_fields)
SELECT r.role_id, p.permission, p.scope, p.hidden_fields
  FROM public.role r
 CROSS JOIN (VALUES
    ('order:read',     'own', ARRAY['sold_for', 'd_net_cost', 'overage', 'commission',
                                    'commission_total', 'project_admin_fee', 'trade_ally_fee']),
    ('invoice:read',   'own', ARRAY[]::text[]),
    ('quote:read',     'own', ARRAY[]::text[]),
    ('quote:write',    'own', ARRAY[]::text[]),
    ('inventory:read', 'all', ARRAY[]::text[]),
    ('document:read',  'all', ARRAY[]::text[]),
    ('dashboard:read', 'own', ARRAY[]::text[])
  ) AS p(permission, scope, hidden_fields)
 WHERE r.code IN ('employee', 'rep', 'customer') AND r.tenant_id IS NULL
ON CONFLICT (role_id, permission) DO NOTHING;

-- Backfill from the columns that carried this until now.
UPDATE public.users u
   SET role_id = r.role_id
  FROM public.role r
 WHERE r.tenant_id IS NULL
   AND r.code = CASE
         WHEN u.is_admin THEN 'admin'
         WHEN u.type IN ('employee', 'rep', 'customer') THEN u.type
         ELSE 'rep'
       END
   AND u.role_id IS NULL;
