-- Support tickets, generalized from MeterItPro's Support module (see
-- framework/backend/db/support_ticket.sql for the canonical shape/comments).
-- TBWC is single-tenant: tenant_id/client_tenant_id stay plain integers,
-- always NULL (no `tenant` table to reference). users_id/assigned_to_users_id
-- are uuid, referencing public.users(id) — Supabase Auth's id, not an
-- integer PK, per TBWC's existing users table.
-- Follows naming convention: {tablename}_id primary keys.

CREATE TABLE IF NOT EXISTS public.support_ticket (
    support_ticket_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id integer,
    client_tenant_id integer,
    users_id uuid REFERENCES public.users(id),
    assigned_to_users_id uuid REFERENCES public.users(id),
    title  varchar(200),
    description text,
    type  varchar(30) NOT NULL DEFAULT 'general',
    status  varchar(20) NOT NULL DEFAULT 'open',
    priority  varchar(20) NOT NULL DEFAULT 'medium',
    resolved_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT support_ticket_type_check CHECK (type::text = ANY (ARRAY['bug'::text, 'feature_request'::text, 'billing'::text, 'account'::text, 'technical'::text, 'general'::text])),
    CONSTRAINT support_ticket_status_check CHECK (status::text = ANY (ARRAY['open'::text, 'in_progress'::text, 'resolved'::text, 'closed'::text])),
    CONSTRAINT support_ticket_priority_check CHECK (priority::text = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'urgent'::text]))
);

CREATE INDEX IF NOT EXISTS idx_support_ticket_users_id ON public.support_ticket USING btree (users_id);
CREATE INDEX IF NOT EXISTS idx_support_ticket_status ON public.support_ticket USING btree (status);
CREATE INDEX IF NOT EXISTS idx_support_ticket_created_at ON public.support_ticket USING btree (created_at);

-- Same blanket-RLS-no-policies stance as every other table here: the Worker
-- connects as the service role and bypasses RLS; anon/authenticated via
-- PostgREST get nothing.
ALTER TABLE public.support_ticket ENABLE ROW LEVEL SECURITY;

-- New permissions (support:read, support:write — see permissions.ts).
-- support:read: 'all' for admin, 'own' for everyone else (sees/files just
-- their own tickets). support:write: admin only.
INSERT INTO public.role_permission (role_id, permission, scope)
SELECT r.role_id, 'support:read', CASE WHEN r.code = 'admin' THEN 'all' ELSE 'own' END
  FROM public.role r
 WHERE r.code IN ('admin', 'employee', 'rep', 'customer') AND r.tenant_id IS NULL
ON CONFLICT (role_id, permission) DO NOTHING;

INSERT INTO public.role_permission (role_id, permission, scope)
SELECT r.role_id, 'support:write', 'all'
  FROM public.role r
 WHERE r.code = 'admin' AND r.tenant_id IS NULL
ON CONFLICT (role_id, permission) DO NOTHING;
