-- AI chat persistent memory (Anthropic memory tool). See
-- framework/backend/db/ai_memory.sql for the canonical shape/comments.
-- TBWC is single-tenant: tenant_id stays NULL, one store for the portal.
-- Follows naming convention: {tablename}_id primary keys.

CREATE TABLE IF NOT EXISTS public.ai_memory (
    ai_memory_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id integer,
    path varchar(500) NOT NULL,
    content text NOT NULL DEFAULT '',
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ai_memory_tenant_path_key UNIQUE NULLS NOT DISTINCT (tenant_id, path),
    CONSTRAINT ai_memory_path_check CHECK (path LIKE '/memories/%')
);

ALTER TABLE public.ai_memory ENABLE ROW LEVEL SECURITY;
